using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Darkengines.Models.Entities {
    public class Property : Member {
        public string? TypeName { get; set; }
        public Type? Type {
            get {
                if (string.IsNullOrWhiteSpace(TypeName)) return null;
                var type = Type.GetType(TypeName, false);
                return type;
            }
        }
        public string? Format { get; set; }
        public bool IsNullable { get; set; }
        public bool IsAutoGenerated { get; set; }
        public int MaximumLength { get; set; }
        public int MinimumLength { get; set; }
    }
}
